"""init: clientes e snapshots

Revision ID: 6a0518ec0d86
Revises: 
Create Date: 2026-05-20 12:08:15.566230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a0518ec0d86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('categoria', sa.Enum('ECOMMERCE', 'LEAD_COM_SITE', 'LEAD_SEM_SITE', name='categoria'), nullable=False),
    sa.Column('setor', sa.String(), nullable=True),
    sa.Column('porte', sa.String(), nullable=True),
    sa.Column('descricao_publica', sa.String(), nullable=True),
    sa.Column('publicar_vitrine', sa.Boolean(), nullable=False),
    sa.Column('destaque', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_publicar_vitrine'), 'clientes', ['publicar_vitrine'], unique=False)
    op.create_index(op.f('ix_clientes_slug'), 'clientes', ['slug'], unique=True)
    op.create_table('snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('periodo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fim', sa.Date(), nullable=False),
    sa.Column('frequencia', sa.Enum('SEMANAL', 'MENSAL', name='frequencia'), nullable=False),
    sa.Column('data_coleta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('faturamento', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('investimento', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('roas', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cpa', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('leads', sa.Integer(), nullable=True),
    sa.Column('vendas', sa.Integer(), nullable=True),
    sa.Column('faturamento_var_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roas_var_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('metricas_detalhadas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_dados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'periodo_inicio', 'periodo_fim', name='uq_snapshot_periodo')
    )
    op.create_index(op.f('ix_snapshots_cliente_id'), 'snapshots', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_snapshots_periodo_fim'), 'snapshots', ['periodo_fim'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshots_periodo_fim'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_cliente_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_clientes_slug'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_publicar_vitrine'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
