"""add_insights

Revision ID: f79fffd5b218
Revises: a1cd4eb9b5c1
Create Date: 2026-05-27 14:16:25.744388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f79fffd5b218'
down_revision: Union[str, Sequence[str], None] = 'a1cd4eb9b5c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('mes', sa.String(length=7), nullable=False),
    sa.Column('sinais', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('narrativa', sa.Text(), nullable=True),
    sa.Column('gerado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'mes', name='uq_insight_cliente_mes')
    )
    op.create_index(op.f('ix_insights_cliente_id'), 'insights', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_insights_mes'), 'insights', ['mes'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insights_mes'), table_name='insights')
    op.drop_index(op.f('ix_insights_cliente_id'), table_name='insights')
    op.drop_table('insights')
    # ### end Alembic commands ###
